// netlify.toml
[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"
    REACT_APP_FIREBASE_API_KEY="AIzaSyBdJag6IMJ9CUC7Bel6vz2GxDlpXdmTSsQ"
    REACT_APP_FIREBASE_AUTH_DOMAIN="shopdse-d3f3d.firebaseapp.com"
    REACT_APP_FIREBASE_DATABASE_URL="https://shopdse-d3f3d-default-rtdb.asia-southeast1.firebasedatabase.app"
    REACT_APP_FIREBASE_PROJECT_ID="shopdse-d3f3d"
    REACT_APP_CLOUDINARY_PRESET="nincosft"
    REACT_APP_CLOUDINARY_URL="https://api.cloudinary.com/v1_1/ddlmeydz0/image/upload"